"""FileOperation functions.

File operations, eg, open close read write.
"""

import logging
from pathlib import Path
from typing import Dict, List

logging.basicConfig(level=logging.DEBUG, format=" %(asctime)s - %(levelname)s - %(message)s")


class FileOperationFunctions:
    """File Operation Functions."""

    def __init__(self) -> None:
        """Init class - vars are called in the function as needed."""

    def __repr__(self) -> str:  # pragma: no cover
        """Display function name using repr."""
        class_name = self.__class__.__name__
        return f"{class_name}"

    @staticmethod
    def build_dictionary(**kwargs: Path) -> Dict[str, object]:
        """Builds dictionary of values.

        input: pathlib path object from the file system
        input_type: Path
        output: output_dict
        output_type: dict
        keys in dictionary:
            Current:
            list of files generated by pathlib
            Future:
            sending to database for now
            future can get other data from pathlib information including:
            subjects
            file_size
            modification date - from pathlib
        """
        input_path: Path = kwargs["input_path"]
        output_dict: Dict[str, object] = dict(
            folders_and_files=list(input_path.rglob("*.*")),
        )
        return output_dict

    @staticmethod
    def get_file_information_build(
        **kwargs: str,
    ) -> List[Dict[str, object]]:
        """Build data about file structure.

        input: input_directory
        input_type = input_directory
        output: output_listing
        output_type = List[str]
        """
        input_directory: str = kwargs["input_directory"]
        path = Path(input_directory)
        folder_list: List[Path] = []
        for each in path.iterdir():
            folder_list.append(each)

        output_listing: List[Dict[str, object]] = []
        for each in folder_list:
            write_to_json: Dict[str, object] = FileOperationFunctions.build_dictionary(input_path=each)
            output_listing.append(write_to_json)
        return output_listing

    @staticmethod
    def filter_file_data(**kwargs: str) -> Dict[str, object]:
        """Filter data.

        input: dictionary_of_paths_in_pathlib_format
        input_type = input_directory
        output: output_dictionary
        output_type = Dict[str]
        """
        input_path: Dict[List[str]] = kwargs["input_path"]
        records_to_add = []
        # create a dictionary of values here
        for each in input_path["folders_and_files"]:
            records_to_add.append(each)
            # print(type(each))

            print(f'each.name {each.name}')
            print(f'each.stat {each.stat}')
            print(f'each.root {each.root}')
            print(f'each.parent {each.parent}')
            print(f'each.parent.parent {each.parent.parent}')
            print(f'each.parent.parent.parent {each.parent.parent.parent}')
            print(f'each.anchor {each.anchor}')
            print(f'each.stat().st_size {each.stat().st_size}')
            print(f'each.stat().st_mtime {each.stat().st_mtime}')
            print(f'each.stat().st_ctime {each.stat().st_ctime}')
            # time will switch based on when function was run


#             file = Path() / 'doc.txt'  # or Path('./doc.txt')
# size = file.stat().st_size
            # could take parent down until we hit root of training and get the subject
            # print(f'each.stat {each.stat}')
            # get it to path and it is easier to get some data

        return dict(
            original_full_path=input_path,
            records_to_add=records_to_add,
            subject="subject_name_from_file_name",
        )
